---
title: "Untitled"
author: "Sarah Mansfield, Alex Baad"
date: "3/27/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, message=F}
library(tseries)
library(forecast)
library(tidyverse)
library(readxl)
library(kableExtra)
```

Goal: Forecast daily demand for January 2011 based on historical data

## Processing the Data

```{r data}
load <- read_excel("data/load.xlsx")
relative_humidity <- read_excel("data/relative_humidity.xlsx")
temperature <- read_excel("data/temperature.xlsx")

# aggregate data
load <- load %>%
  select(-meter_id) %>%
  mutate(daily_avg_load = rowMeans(select(., starts_with("h")), na.rm = TRUE)) %>%
  select(date, daily_avg_load)

relative_humidity <- relative_humidity %>%
  mutate(avg = rowMeans(select(., starts_with("rh")), na.rm = TRUE)) %>%
  group_by(date) %>%
  summarise(daily_avg_humidity = mean(avg))

temperature <- temperature %>%
  mutate(avg = rowMeans(select(., starts_with("t")), na.rm = TRUE)) %>%
  group_by(date) %>%
  summarise(daily_avg_temp = mean(avg))

df <- inner_join(load, relative_humidity) %>%
  inner_join(temperature)
```

```{r}
ggplot(load, aes(x = date, y = daily_avg_load)) +
  geom_line() +
  theme_bw()

ggplot(relative_humidity, aes(x = date, y = daily_avg_humidity)) +
  geom_line() +
  theme_bw()

ggplot(temperature, aes(x = date, y = daily_avg_temp)) +
  geom_line() +
  theme_bw()
```


## Creating the Time-Series object

```{r}
load_ts <- msts(df$daily_avg_load, seasonal.periods = c(7, 365.25), start = c(2005, 1, 1))

load_ts %>%
  mstl() %>%
  autoplot() +
  theme_bw()
```

## Fitting Models and Forecasting for 2010

```{r}
n_for = 365

# training data
load_ts_train <- subset(load_ts, end = length(load_ts) - n_for)
# test data
load_ts_test <- subset(load_ts, start = length(load_ts) - n_for + 1)

autoplot(load_ts_train) +
  theme_bw()
autoplot(load_ts_test) +
  theme_bw()

df_train <- df %>%
  slice(1:(length(load_ts) - n_for)) %>%
  select(daily_avg_humidity, daily_avg_temp) %>%
  as.matrix()
df_test <- df %>%
  slice((length(load_ts) - n_for + 1):length(load_ts)) %>%
  select(daily_avg_humidity, daily_avg_temp) %>%
  as.matrix()
```

### Model 1: STL + ETS

```{r}
ETS_fit <- stlf(load_ts_train, h=365)

# plot forecast results
autoplot(ETS_fit) + 
  ylab("Load") +
  theme_bw()

# plot model + observed data
autoplot(load_ts) +
  autolayer(ETS_fit, series = "STL + ETS", PI = FALSE) +
  ylab("Load") +
  theme_bw()
```

## Model 2: ARIMA + Fourier Terms

```{r}
#Fit arima model with fourier terms as exogenous variables
#Starting with k=(2,2)
ARIMA_Four_fit_2 <- forecast::auto.arima(load_ts_train, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=fourier(load_ts_train, 
                                          K=c(2,2))
                             )
#Forecast with ARIMA fit
ARIMA_Four_for_2 <- forecast::forecast(ARIMA_Four_fit_2,
                           xreg=fourier(load_ts_train,
                                        K=c(2,2),
                                        h=365),
                           h=365
                           ) 
#Plot foresting results
autoplot(ARIMA_Four_for_2) + 
  ylab("Load") +
  theme_bw()

#Plot model + observed data
autoplot(load_ts) +
  autolayer(ARIMA_Four_for_2, series="ARIMA_FOURIER_2,2",PI=FALSE) +
  ylab("Load") +
  theme_bw()

#Arima+Fourier(2,4)
ARIMA_Four_fit_4 <- forecast::auto.arima(load_ts_train, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=fourier(load_ts_train, 
                                          K=c(2,4))
                             )
#Forecast with ARIMA fit
ARIMA_Four_for_4 <- forecast::forecast(ARIMA_Four_fit_4,
                           xreg=fourier(load_ts_train,
                                        K=c(2,4),
                                        h=365),
                           h=365
                           ) 
#Plot foresting results
autoplot(ARIMA_Four_for_4) + 
  ylab("Load") +
  theme_bw()

#Plot model + observed data
autoplot(load_ts) +
  autolayer(ARIMA_Four_for_4, series="ARIMA_FOURIER_2,4",PI=FALSE) +
  ylab("Load") +
  theme_bw()

#Arima+Fourier(2,6)
ARIMA_Four_fit_6 <- forecast::auto.arima(load_ts_train, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=fourier(load_ts_train, 
                                          K=c(2,6))
                             )
#Forecast with ARIMA fit
ARIMA_Four_for_6 <- forecast::forecast(ARIMA_Four_fit_6,
                           xreg=fourier(load_ts_train,
                                        K=c(2,6),
                                        h=365),
                           h=365
                           ) 
#Plot foresting results
autoplot(ARIMA_Four_for_6) + 
  ylab("Load") +
  theme_bw()

#Plot model + observed data
autoplot(load_ts) +
  autolayer(ARIMA_Four_for_6, series="ARIMA_FOURIER_2,6",PI=FALSE) +
  ylab("Load") +
  theme_bw()

#Arima+Fourier(2,12)
ARIMA_Four_fit_12 <- forecast::auto.arima(load_ts_train, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=fourier(load_ts_train, 
                                          K=c(2,12))
                             )
#Forecast with ARIMA fit
ARIMA_Four_for_12 <- forecast::forecast(ARIMA_Four_fit_12,
                           xreg=fourier(load_ts_train,
                                        K=c(2,12),
                                        h=365),
                           h=365
                           ) 
#Plot foresting results
autoplot(ARIMA_Four_for_12) + 
  ylab("Load") +
  theme_bw()

#Plot model + observed data
autoplot(load_ts) +
  autolayer(ARIMA_Four_for_12, series="ARIMA_FOURIER_2,12",PI=FALSE) +
  ylab("Load") +
  theme_bw()
```

## Model 3: TBATS

```{r}
TBATS_fit <- tbats(load_ts_train)

TBATS_for <- forecast(TBATS_fit, h=365)

#Plot forecasting results
autoplot(TBATS_for) +
  ylab("Load") 

#Plot model + observed data
autoplot(load_ts) +
  autolayer(TBATS_for, series="TBATS",PI=FALSE)+
  ylab("Load") 
```

## Model 4: Neural Network

```{r}
#p=1 P=1 no xreg
NN_fit_1 <- nnetar(load_ts_train,p=1,P=1)
NN_for_1 <- forecast(NN_fit_1, h=365)

#Plot foresting results
autoplot(NN_for_1) +
  ylab("Active Power") 

#Plot model + observed data
autoplot(load_ts) +
  autolayer(NN_for_1, series="Neural Network No xreg",PI=FALSE)+
  ylab("Active Power") 

#p=1 P=0 xreg fourier
NN_fit_2 <- nnetar(load_ts_train,p=1,P=0,xreg=fourier(load_ts_train, K=c(2,12)))
NN_for_2 <- forecast(NN_fit_2, h=365,xreg=fourier(load_ts_train, 
                                          K=c(2,12),h=365))
#Plot foresting results
autoplot(NN_for_2) +
  ylab("Active Power") 

#Plot model + observed data
autoplot(load_ts) +
  autolayer(NN_for_2, series="Neural Network Fourier",PI=FALSE)+
  ylab("Active Power") 

```

## Model 5: Seasonal Naive

```{r}
SNAIVE_seas <- snaive(load_ts_train, h=365)

autoplot(SNAIVE_seas) +
  ylab("Load") 

#Plot model + observed data
autoplot(load_ts) +
  autolayer(SNAIVE_seas, series="SNAIVE",PI=FALSE)+
  ylab("Load") 
```

## Model 6: SARIMA

```{r}
SARIMA_autofit <- auto.arima(load_ts_train, D=1)
SARIMA_for <- forecast(SARIMA_autofit, h=365)

autoplot(SARIMA_for) +
  ylab("Load") 

#Plot model + observed data
autoplot(load_ts) +
  autolayer(SARIMA_for, series="SARIMA",PI=FALSE)+
  ylab("Load") 
```




## Comparing Models

```{r}
# model 1: STL + ETS
ETS_scores <- accuracy(ETS_fit$mean, load_ts_test)

#model 2: Arima + Fourier
ARIMA_2_scores <- accuracy(ARIMA_Four_for_2$mean, load_ts_test)
ARIMA_4_scores <- accuracy(ARIMA_Four_for_4$mean, load_ts_test)
ARIMA_6_scores <- accuracy(ARIMA_Four_for_6$mean, load_ts_test)
ARIMA_12_scores <- accuracy(ARIMA_Four_for_12$mean, load_ts_test)

#model 3: TBATS
TBATS_scores <- accuracy(TBATS_for$mean,load_ts_test)

#model 4: NN
NN_1_scores <- accuracy(NN_for_1$mean,load_ts_test)
NN_2_scores <- accuracy(NN_for_2$mean,load_ts_test)

#model 4: seasonal naive
SNAIVE_scores <- accuracy(SNAIVE_seas$mean, load_ts_test)

#model 5: SARIMA
SARIMA_scores <- accuracy(SARIMA_for$mean, load_ts_test)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
#create data frame
scores <- as.data.frame(
  rbind(ETS_scores, ARIMA_2_scores, ARIMA_4_scores, ARIMA_6_scores, ARIMA_12_scores,
        TBATS_scores, NN_1_scores, NN_2_scores, SNAIVE_scores, SARIMA_scores)
  )
row.names(scores) <- c("STL+ETS", "ARIMA+Fourier k(2,2)", "ARIMA+Fourier k(2,4)", 
                       "ARIMA+Fourier k(2,6)", "ARIMA+Fourier k(2,12)", "TBATS", 
                       "NN no xreg", "NN Fourier", "SNAIVE", "SARIMA")

kbl(scores, 
      caption = "Forecast Accuracy for Daily Average Load",
      digits = array(5,ncol(scores))) %>%
  kable_styling(full_width = FALSE, position = "center", latex_options = "hold_position") %>%
  #highlight model with lowest RMSE
  kable_styling(latex_options="striped", stripe_index = which.min(scores[,"RMSE"]))
```


## Predicting January 2011

```{r eval=F}
submission_template <- read_excel("submission_template.xlsx",
                                  sheet = "p90", n_max = 31)
```

```{r eval=F}
# fitting models on all the data
n_for <- 31

#ETS
ETS_fit <- stlf(load_ts, h=n_for)

#ARIMA + Fourier
ARIMA_Four_fit_2 <- forecast::auto.arima(load_ts, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=fourier(load_ts, 
                                          K=c(2,2))
                             )
ARIMA_Four_for_2 <- forecast::forecast(ARIMA_Four_fit_2,
                           xreg=fourier(load_ts,
                                        K=c(2,2),
                                        h=n_for),
                           h=n_for
                           ) 
ARIMA_Four_fit_4 <- forecast::auto.arima(load_ts, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=fourier(load_ts, 
                                          K=c(2,4))
                             )
ARIMA_Four_for_4 <- forecast::forecast(ARIMA_Four_fit_4,
                           xreg=fourier(load_ts,
                                        K=c(2,4),
                                        h=n_for),
                           h=n_for
                           ) 
ARIMA_Four_fit_6 <- forecast::auto.arima(load_ts, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=fourier(load_ts, 
                                          K=c(2,6))
                             )
ARIMA_Four_for_6 <- forecast::forecast(ARIMA_Four_fit_6,
                           xreg=fourier(load_ts,
                                        K=c(2,6),
                                        h=n_for),
                           h=n_for
                           )
ARIMA_Four_fit_12 <- forecast::auto.arima(load_ts, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=fourier(load_ts, 
                                          K=c(2,12))
                             )
ARIMA_Four_for_12 <- forecast::forecast(ARIMA_Four_fit_12,
                           xreg=fourier(load_ts,
                                        K=c(2,12),
                                        h=n_for),
                           h=n_for
                           )
#TBATS
TBATS_fit <- tbats(load_ts)
TBATS_for <- forecast(TBATS_fit, h=n_for)

#NN
NN_fit_1 <- nnetar(load_ts,p=1,P=1)
NN_for_1 <- forecast(NN_fit_1, h=n_for)

NN_fit_2 <- nnetar(load_ts,p=1,P=0,xreg=fourier(load_ts, K=c(2,12)))
NN_for_2 <- forecast(NN_fit_2, h=n_for,xreg=fourier(load_ts, 
                                          K=c(2,12),h=n_for))

#SNAIVE
SNAIVE_fit <- snaive(load_ts, h=n_for)

#SARIMA
SARIMA_fit <- Arima(load_ts, order=c(4,0,2), seasonal=c(0,1,0), include.drift = TRUE)
SARIMA_for <- forecast(SARIMA_fit, h=n_for)
```

```{r eval=F}
# build kaggle submission file
submission_template$load <- ETS_fit$mean
submission_template$load <- ARIMA_Four_for_2$mean
submission_template$load <- ARIMA_Four_for_4$mean
submission_template$load <- ARIMA_Four_for_6$mean
submission_template$load <- NN_for_1$mean
submission_template$load <- NN_for_2$mean
submission_template$load <- SNAIVE_fit$mean
submission_template$load <- SARIMA_for$mean

# change the path name for each submission file
write.csv(submission_template, "kaggle_submissions/sub4.csv", row.names = FALSE)
write.csv(submission_template, "kaggle_submissions/sub5.csv", row.names = FALSE)
write.csv(submission_template, "kaggle_submissions/sub6.csv", row.names = FALSE)
write.csv(submission_template, "kaggle_submissions/sub7.csv", row.names = FALSE)
write.csv(submission_template, "kaggle_submissions/sub8.csv", row.names = FALSE)
write.csv(submission_template, "kaggle_submissions/sub9.csv", row.names = FALSE)
write.csv(submission_template, "kaggle_submissions/sub10.csv", row.names = FALSE)
write.csv(submission_template, "kaggle_submissions/sub11.csv", row.names = FALSE)
```





